all: ex2_1 ex2_2 ex2_3
	
ex2_1: TestMutableInteger.java
	javac TestMutableInteger.java

ex2_2: TestCountPrimes.java
	javac TestCountPrimes.java

ex2_3: TestCountFactors.java
	javac TestCountFactors.java

clean:
	rm -f *.class